# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=25)),
                ('employee_id', models.CharField(max_length=10)),
                ('asset_type', models.CharField(choices=[('L', 'Laptop'), ('P', 'Printer'), ('S', 'Scanner'), ('D', 'Desktop'), ('K', 'Keyboard'), ('M', 'Mouse'), ('O', 'Others')], max_length=1)),
                ('date_of_issue', models.DateTimeField()),
                ('date_of_submission', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
