# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_of_issue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_of_submission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
