# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='asset_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Desktop', 'Desktop'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Others', 'Others')], max_length=8),
        ),
    ]
