# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20181228_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='asset_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date_of_submission',
            new_name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_of_issue',
        ),
        migrations.RemoveField(
            model_name='item',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='asset_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Desktop', 'Desktop'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Modem', 'Modem'), ('Router', 'Router'), ('Switch', 'Switch'), ('Others', 'Others')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='configuration',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='hostname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='operating_system',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='plant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='asset_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
