# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20181229_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Asset',
        ),
    ]
