# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20181229_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='model',
        ),
    ]
