# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateuser',
            name='otp',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
